import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-700 min-h-screen flex justify-center items-center">
        <h1 className ="text-white font-bold text-4xl">WIBU SAMA</h1>
      </main>

      <footer className="">
        
      </footer>
    </div>
  )
}
